name: r08fullmovieapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.16.0
  animated_splash_screen: ^1.3.0
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  fluttertoast: ^8.2.10
  font_awesome_flutter: ^9.2.0
  http: ^1.2.2
  image_cropper: ^8.1.0
  image_picker: ^1.1.2
  path: any
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5
  sqflite: ^2.4.1
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  youtube_player_flutter: ^9.1.1
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.13.0
  speech_to_text: ^7.1.0
  permission_handler: ^11.3.1
  translator: ^1.0.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/user.png
    - assets/movie_banner.jpg
    - assets/movie_logo.jpg
    - .env

# ðŸ‘‡ Cáº¥u hÃ¬nh icon cho app (sá»­ dá»¥ng logo báº¡n Ä‘Ã£ gá»­i)
flutter_icons:
  android: true
  ios: true
  image_path: assets/icon.png

# ðŸ‘‡ Cáº¥u hÃ¬nh splash screen (mÃ n hÃ¬nh khá»Ÿi Ä‘á»™ng)
flutter_native_splash:
  color: "#ffffff"
  image: assets/icon.png
  android: true
  ios: true
